//go:build go1.22

// Package sentinel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sentinel

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Decision.
const (
	Approve   Decision = "approve"
	Escalate  Decision = "escalate"
	Modify    Decision = "modify"
	Reject    Decision = "reject"
	Terminate Decision = "terminate"
)

// Defines values for Status.
const (
	Completed  Status = "completed"
	Processing Status = "processing"
	Queued     Status = "queued"
	Timeout    Status = "timeout"
)

// Arguments defines model for Arguments.
type Arguments struct {
	Cmd  *string `json:"cmd,omitempty"`
	Code *string `json:"code,omitempty"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Content   string      `json:"content"`
	Role      string      `json:"role"`
	Source    *string     `json:"source,omitempty"`
	ToolCalls *[]ToolCall `json:"tool_calls,omitempty"`
}

// Choice defines model for Choice.
type Choice struct {
	Message    AssistantMessage `json:"message"`
	StopReason *string          `json:"stop_reason,omitempty"`
}

// CodeSnippet defines model for CodeSnippet.
type CodeSnippet struct {
	Text string `json:"text"`
}

// Decision defines model for Decision.
type Decision string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Status string `json:"status"`
}

// HubStats defines model for HubStats.
type HubStats struct {
	AssignedReviews    map[string]int `json:"assigned_reviews"`
	BusyClients        int            `json:"busy_clients"`
	CompletedReviews   int            `json:"completed_reviews"`
	ConnectedClients   int            `json:"connected_clients"`
	FreeClients        int            `json:"free_clients"`
	QueuedReviews      int            `json:"queued_reviews"`
	ReviewDistribution map[string]int `json:"review_distribution"`
	StoredReviews      int            `json:"stored_reviews"`
}

// LLMExplanation defines model for LLMExplanation.
type LLMExplanation struct {
	Explanation string  `json:"explanation"`
	Score       float32 `json:"score"`
}

// Message defines model for Message.
type Message struct {
	Content    string      `json:"content"`
	Function   *string     `json:"function,omitempty"`
	Role       string      `json:"role"`
	Source     *string     `json:"source,omitempty"`
	ToolCallId *string     `json:"tool_call_id,omitempty"`
	ToolCalls  *[]ToolCall `json:"tool_calls,omitempty"`
}

// Output defines model for Output.
type Output struct {
	Choices *[]Choice `json:"choices,omitempty"`
	Model   *string   `json:"model,omitempty"`
	Usage   *Usage    `json:"usage,omitempty"`
}

// Review defines model for Review.
type Review struct {
	Id      string        `json:"id"`
	Request ReviewRequest `json:"request"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	AgentId      string       `json:"agent_id"`
	LastMessages []Message    `json:"last_messages"`
	TaskState    TaskState    `json:"task_state"`
	ToolChoices  []ToolChoice `json:"tool_choices"`
}

// ReviewResult defines model for ReviewResult.
type ReviewResult struct {
	Decision   Decision   `json:"decision"`
	Id         string     `json:"id"`
	Reasoning  string     `json:"reasoning"`
	ToolChoice ToolChoice `json:"tool_choice"`
}

// ReviewStatusResponse defines model for ReviewStatusResponse.
type ReviewStatusResponse struct {
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// Status defines model for Status.
type Status string

// TaskState defines model for TaskState.
type TaskState struct {
	Completed  bool                    `json:"completed"`
	Messages   []Message               `json:"messages"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Output     Output                  `json:"output"`
	Store      *map[string]interface{} `json:"store,omitempty"`
	ToolChoice *ToolChoice             `json:"tool_choice,omitempty"`
	Tools      []Tool                  `json:"tools"`
}

// Tool defines model for Tool.
type Tool struct {
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Arguments  map[string]interface{} `json:"arguments"`
	Function   string                 `json:"function"`
	Id         string                 `json:"id"`
	ParseError *string                `json:"parse_error,omitempty"`
	Type       string                 `json:"type"`
}

// ToolChoice defines model for ToolChoice.
type ToolChoice struct {
	Arguments Arguments `json:"arguments"`
	Function  string    `json:"function"`
	Id        string    `json:"id"`
	Type      string    `json:"type"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

// GetReviewLLMParams defines parameters for GetReviewLLM.
type GetReviewLLMParams struct {
	Id string `form:"id" json:"id"`
}

// GetReviewRequestParams defines parameters for GetReviewRequest.
type GetReviewRequestParams struct {
	Id string `form:"id" json:"id"`
}

// GetReviewResultParams defines parameters for GetReviewResult.
type GetReviewResultParams struct {
	Id string `form:"id" json:"id"`
}

// GetLLMExplanationJSONRequestBody defines body for GetLLMExplanation for application/json ContentType.
type GetLLMExplanationJSONRequestBody = CodeSnippet

// SubmitReviewJSONRequestBody defines body for SubmitReview for application/json ContentType.
type SubmitReviewJSONRequestBody = ReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get an explanation and danger score for a code snippet
	// (POST /api/explain)
	GetLLMExplanation(w http.ResponseWriter, r *http.Request)
	// Submit a review request
	// (POST /api/review/human)
	SubmitReview(w http.ResponseWriter, r *http.Request)
	// Get the LLM's reasoning for a review decision
	// (POST /api/review/llm)
	GetReviewLLM(w http.ResponseWriter, r *http.Request, params GetReviewLLMParams)
	// See the request that was made for a given review ID
	// (GET /api/review/request)
	GetReviewRequest(w http.ResponseWriter, r *http.Request, params GetReviewRequestParams)
	// Get the status of a review request
	// (GET /api/review/status)
	GetReviewResult(w http.ResponseWriter, r *http.Request, params GetReviewResultParams)
	// Get hub statistics
	// (GET /api/stats)
	GetHubStats(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLLMExplanation operation middleware
func (siw *ServerInterfaceWrapper) GetLLMExplanation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMExplanation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitReview operation middleware
func (siw *ServerInterfaceWrapper) SubmitReview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewLLM operation middleware
func (siw *ServerInterfaceWrapper) GetReviewLLM(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewLLMParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewLLM(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewRequest operation middleware
func (siw *ServerInterfaceWrapper) GetReviewRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewRequestParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewRequest(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewResult operation middleware
func (siw *ServerInterfaceWrapper) GetReviewResult(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewResultParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewResult(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHubStats operation middleware
func (siw *ServerInterfaceWrapper) GetHubStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHubStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/explain", wrapper.GetLLMExplanation)
	m.HandleFunc("POST "+options.BaseURL+"/api/review/human", wrapper.SubmitReview)
	m.HandleFunc("POST "+options.BaseURL+"/api/review/llm", wrapper.GetReviewLLM)
	m.HandleFunc("GET "+options.BaseURL+"/api/review/request", wrapper.GetReviewRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/review/status", wrapper.GetReviewResult)
	m.HandleFunc("GET "+options.BaseURL+"/api/stats", wrapper.GetHubStats)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYTW/bOBP+KwLfAu/FiNPdnnxL22AbwEEDu+keikCgpbHNhiJVcujWCPzfFyT1LUp2",
	"0qRoT3Gk4cwzD+dTDySRWS4FCNRk9kB0soWMup8XamOy8nmuZA4KGbj/kiy1f3CfA5kRjYqJDTlMSCJT",
	"CLw4TMoncvUVErSiF1ozjVTgNWhNNxAwIgWCwKAhJTkEX2hpVBJ+hVLyOKGcO+0MIXM/XilYkxn537Qm",
	"YlqwMP0kJX9HOSe1B1QpuncuKfhmmIKUzL5UWAtkdwGH320lSwJuZrX/Y1B6fFlnUeaxAqqlCLPehFja",
	"CWKTKSwFy3PAPkCEH3hcvZMK6X4PCdPMIwRhMitM81zJHVi6wMlNCOiEcor2GYLKmPC/M5my9b6huL7P",
	"S6WkWoDOpdABXjVSNPo48EIuBP2DWS2RhhKAas02AtJYwY7Bd/8sTRkyKSi/afPn1TKBsAFFQsmwMnof",
	"J5yV2dY/YiOCA7YthsSEgMSKjWpbK4BxiW8GzDFj/mWcMsvsymBxyT/Bg0apxq32867jbw96T2vH/Q77",
	"k/7dhj0N3UkoiObz68sfOaeClgS1QwnaL/sVLZGqWdCEyVYBJppqykMhOE8qt2sjkkGAP1WLY5b+jsX6",
	"o8HcBGph4or46ZiKot9D5Aob8KDr5pR2cOt7QCiJFi4Y+9gHmLbMgMZjBr3WRSHcpZSlpNZ0NwhqUdvq",
	"1NMNCByKBU41xkX7Op36Rp/sco9U38e27h+l+RPV90snWMXkIyPAReVAFHRIrEhoIezY7dIxRrY2PMB1",
	"2mjIY8irxn2YDMeOnT3sP8M5XI09p7IUCq0Kc1trE8EwEUvX4YcnhQHn6gFiDLlXHkY9MlosK+XlTOTb",
	"FplYcAlobVE0eoz1nGUgDQaHoTpQA4W9VFF7uZKSA3VX+5yJlQHSlCIdHgNQGQjQIat6O2a5qMrloPBo",
	"K08MSH/wcSl/NNkr2kvtFQnNSw+FjlPfr6DoRxPQj6YlBZ0olg82eEEzOD5HO6khvK4v9zE3N8xHQR4d",
	"SAbyOadKQwx2awiXK/fgmJsusSvzk4YPhYZBCgb2vxYJoxtgJfhEAl7QwdvwTMlEbjBGeQ9iYAXwMT8q",
	"ghIpH5Ho4m/a7BroaOu7YrUxsZbOEEM72ZIlCGQCeHRxc0UmZAfKt0/y+uz87Nx5kYOgOSMz8vfZ+dlr",
	"W8Qpbh3aKc3Z1A3nzA//0s8/liY3rV+lZEb+AezsCdU49Vam+858TvOcs8TJTb8Wy7+PkqPzaGPRP7SZ",
	"s5nmHvg26cD/dX7+bKY7/jnrrcpjN6WoscZEClAx2EEaaZPYlrg2nLs+8+YZcbU/IwRgvaVppBpzrzZZ",
	"RtXe31pERQszFWmUUrEBFbkdLFpLFdEokSlEuiJ+4sPCr43TrcnoSGwszSpjWEz1LxMW3eH+lwZGcEgL",
	"3IOXi/yc1AmJ1rV4wiIaeX5bl9fknfNsNCO9wfn82uWzohkgKE1mX2xhIzM7sak9KftjvQPVtE0aFHSr",
	"7t3vQ6lNvKFk6wU8bsEe+L+Oqtm7CPKC7mpW7/Ld2DQ3MEZ5GYh/Ju0jRBcMnEb2EsCRXR7CLcXoO9VR",
	"RtOyrmzYDkRJ/NX7HuX1DnOMcbcr/pmEF+CHafcsjPaTN7+unxSghMRoLY1IB3KsAC3XI4VMl1+nh263",
	"+oL9gpdQ2Qj4+sGsnCNMI0v06UVm2zrnNWtQuzIujeJkRl49XNzcLD5+vpjH/16+XV4uPl8u4tvF/EAO",
	"d4f/AgAA//8aGYcf2hoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
