//go:build go1.22

// Package sentinel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sentinel

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Decision.
const (
	Approve   Decision = "approve"
	Escalate  Decision = "escalate"
	Modify    Decision = "modify"
	Reject    Decision = "reject"
	Terminate Decision = "terminate"
)

// Defines values for Status.
const (
	Completed  Status = "completed"
	Processing Status = "processing"
	Queued     Status = "queued"
	Timeout    Status = "timeout"
)

// Arguments defines model for Arguments.
type Arguments struct {
	Cmd  *string `json:"cmd,omitempty"`
	Code *string `json:"code,omitempty"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Content   string      `json:"content"`
	Role      string      `json:"role"`
	Source    *string     `json:"source,omitempty"`
	ToolCalls *[]ToolCall `json:"tool_calls,omitempty"`
}

// Choice defines model for Choice.
type Choice struct {
	Message    AssistantMessage `json:"message"`
	StopReason *string          `json:"stop_reason,omitempty"`
}

// CodeSnippet defines model for CodeSnippet.
type CodeSnippet struct {
	Text string `json:"text"`
}

// Decision defines model for Decision.
type Decision string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Status string `json:"status"`
}

// HubStats defines model for HubStats.
type HubStats struct {
	AssignedReviews    map[string]int `json:"assigned_reviews"`
	BusyClients        int            `json:"busy_clients"`
	CompletedReviews   int            `json:"completed_reviews"`
	ConnectedClients   int            `json:"connected_clients"`
	FreeClients        int            `json:"free_clients"`
	QueuedReviews      int            `json:"queued_reviews"`
	ReviewDistribution map[string]int `json:"review_distribution"`
	StoredReviews      int            `json:"stored_reviews"`
}

// LLMExplanation defines model for LLMExplanation.
type LLMExplanation struct {
	Explanation string  `json:"explanation"`
	Score       float32 `json:"score"`
}

// Message defines model for Message.
type Message struct {
	Content    string      `json:"content"`
	Function   *string     `json:"function,omitempty"`
	Role       string      `json:"role"`
	Source     *string     `json:"source,omitempty"`
	ToolCallId *string     `json:"tool_call_id,omitempty"`
	ToolCalls  *[]ToolCall `json:"tool_calls,omitempty"`
}

// Output defines model for Output.
type Output struct {
	Choices *[]Choice `json:"choices,omitempty"`
	Model   *string   `json:"model,omitempty"`
	Usage   *Usage    `json:"usage,omitempty"`
}

// Review defines model for Review.
type Review struct {
	Id      string        `json:"id"`
	Request ReviewRequest `json:"request"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	AgentId      string       `json:"agent_id"`
	LastMessages []Message    `json:"last_messages"`
	TaskState    TaskState    `json:"task_state"`
	ToolChoices  []ToolChoice `json:"tool_choices"`
}

// ReviewResult defines model for ReviewResult.
type ReviewResult struct {
	Decision   Decision   `json:"decision"`
	Id         string     `json:"id"`
	Reasoning  string     `json:"reasoning"`
	ToolChoice ToolChoice `json:"tool_choice"`
}

// ReviewStatusResponse defines model for ReviewStatusResponse.
type ReviewStatusResponse struct {
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// Status defines model for Status.
type Status string

// TaskState defines model for TaskState.
type TaskState struct {
	Completed  bool                    `json:"completed"`
	Messages   []Message               `json:"messages"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Output     Output                  `json:"output"`
	Store      *map[string]interface{} `json:"store,omitempty"`
	ToolChoice *ToolChoice             `json:"tool_choice,omitempty"`
	Tools      []Tool                  `json:"tools"`
}

// Tool defines model for Tool.
type Tool struct {
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Arguments  map[string]interface{} `json:"arguments"`
	Function   string                 `json:"function"`
	Id         string                 `json:"id"`
	ParseError *string                `json:"parse_error,omitempty"`
	Type       string                 `json:"type"`
}

// ToolChoice defines model for ToolChoice.
type ToolChoice struct {
	Arguments Arguments `json:"arguments"`
	Function  string    `json:"function"`
	Id        string    `json:"id"`
	Type      string    `json:"type"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

// GetReviewRequestParams defines parameters for GetReviewRequest.
type GetReviewRequestParams struct {
	Id string `form:"id" json:"id"`
}

// GetReviewResultParams defines parameters for GetReviewResult.
type GetReviewResultParams struct {
	Id string `form:"id" json:"id"`
}

// GetLLMExplanationJSONRequestBody defines body for GetLLMExplanation for application/json ContentType.
type GetLLMExplanationJSONRequestBody = CodeSnippet

// SubmitReviewJSONRequestBody defines body for SubmitReview for application/json ContentType.
type SubmitReviewJSONRequestBody = ReviewRequest

// SubmitReviewLLMJSONRequestBody defines body for SubmitReviewLLM for application/json ContentType.
type SubmitReviewLLMJSONRequestBody = ReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get an explanation and danger score for a code snippet
	// (POST /api/explain)
	GetLLMExplanation(w http.ResponseWriter, r *http.Request)
	// Submit a review request for human review
	// (POST /api/review/human)
	SubmitReview(w http.ResponseWriter, r *http.Request)
	// Submit a review request for LLM review
	// (POST /api/review/llm)
	SubmitReviewLLM(w http.ResponseWriter, r *http.Request)
	// See the request that was made for a given review ID
	// (GET /api/review/request)
	GetReviewRequest(w http.ResponseWriter, r *http.Request, params GetReviewRequestParams)
	// Get the status of a review request
	// (GET /api/review/status)
	GetReviewResult(w http.ResponseWriter, r *http.Request, params GetReviewResultParams)
	// Get hub statistics
	// (GET /api/stats)
	GetHubStats(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLLMExplanation operation middleware
func (siw *ServerInterfaceWrapper) GetLLMExplanation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMExplanation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitReview operation middleware
func (siw *ServerInterfaceWrapper) SubmitReview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitReviewLLM operation middleware
func (siw *ServerInterfaceWrapper) SubmitReviewLLM(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReviewLLM(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewRequest operation middleware
func (siw *ServerInterfaceWrapper) GetReviewRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewRequestParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewRequest(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewResult operation middleware
func (siw *ServerInterfaceWrapper) GetReviewResult(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewResultParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewResult(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHubStats operation middleware
func (siw *ServerInterfaceWrapper) GetHubStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHubStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/explain", wrapper.GetLLMExplanation)
	m.HandleFunc("POST "+options.BaseURL+"/api/review/human", wrapper.SubmitReview)
	m.HandleFunc("POST "+options.BaseURL+"/api/review/llm", wrapper.SubmitReviewLLM)
	m.HandleFunc("GET "+options.BaseURL+"/api/review/request", wrapper.GetReviewRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/review/status", wrapper.GetReviewResult)
	m.HandleFunc("GET "+options.BaseURL+"/api/stats", wrapper.GetHubStats)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYzW7bOBB+FYHboxGnuz35lrbBNoCDBnbTPRSBQEtjmw1FquTQrRH43Rck9S9KdtKk",
	"6AJ7iiONZ7755t8PJJFZLgUI1GT2QHSyhYy6jxdqY7Lyea5kDgoZuP+SLLV/cJ8DmRGNiokNOUxIIlMI",
	"vDhMyidy9RUStKIXWjONVOA1aE03EDAiBYLAoCElOQRfaGlUEn6FUvI4oZw77Qwhcx9eKViTGfljWhMx",
	"LViYfpKSv6Ock9oDqhTdO5cUfDNMQUpmXyqsBbK7gMPvtpIlATez2v8xKD2+rLMo81gB1VKEWW9CLO0E",
	"sckUloLlOWAfIMIPPK7eSYV0v4eEaeYRgjCZFaZ5ruQOLF3g5CYEdEI5RfsMQWVM+M+ZTNl631Bcx/NS",
	"KakWoHMpdIBXjRSNPg68kAtB/2BWS6ShAqBas42ANFawY/DdP0tThkwKym/a/Hm1TCBsQJFQMayM3scJ",
	"Z2W19b9iM4IDti2GxISAxIqNalsrgHGJbwbMMWP+ZZwyy+zKYBHkn+BBo1TjVvt11/G3B72nteN+h/1J",
	"P7ZhT0MxCSXRfH59+SPnVNCSoHYqQftlv6MlUjUbmjDZKsBEU035pRCcJ7XbtRHJIMCf6sUxS3/HZv3R",
	"YG4CvTBxTfx0TEXT7yFyjQ140HVzyji49TMgVEQLl4x97ANMW2ZA4zGDXuuiEO5SylJSa7obBLWobXX6",
	"6QYEDuUCpxrjYnydTn1jTna5R6rvY9v3j9L8ier7pROscvKRGeCyciALOiRWJLQQdux26RgjWxse4Dpt",
	"DOQx5NXgPkyGc8fuHvaf4Rqu1p5TWQqlVoW5rbWJYJiIpZvww5vCgHP1AjGG3CsPox5ZLZaV8nIn8mOL",
	"TCy4BLS2KBozxnrOMpAGg8tQnaiBxl6qqL1cScmButA+Z2FlgDSlSIfXAFQGAnTIqt+OWS66crkoPNrK",
	"ExPSf/FxJX+02CvaS+0VCc2gh1LHqe93UPSrCehH05KCThTLBwe8oBkc36Od1BBeN5f7mJsX5qMgjy4k",
	"A/WcU6UhBns1hNuVe3DMTVfYlflJw4dCwyAFA/dfi4TRC7ASfCIBL+jgbXinZCI3GKO8BzFwAvicHxVB",
	"iZSPSHTxN212DXS09V2x2phYS2eIod1syRIEMgE8uri5IhOyA+XHJ3l9dn527rzIQdCckRn56+z87LVt",
	"4hS3Du2U5mzqlnPml3/p9x9Lk9vWr1IyI38Ddu6Eap16K9N9Zz+nec5Z4uSmX4vj32fJ0X20cegf2szZ",
	"SnMP/Jh04P88P3820x3/nPVW57GXUtQ4YyIFqBjsII20SexIXBvO3Zx584y42j8jBGC9pWmkGnuvNllG",
	"1d5HLaKihZmKNEqp2ICK3A0WraWKaJTIFCJdET/xaeHPxunWZHQkN5ZmlTEstvqXSYvucv9LEyO4pAXi",
	"4OUivyd1UqIVFk9YRCPPbxk8FwrHdfGiFwjOs9PCMJ9f/x+JcCR+m+IcywLbaQZyoHEObyDcqdsxcosF",
	"zQBBaTL7YocemdltXu1JuTvV93EdyEmDgu5EvnvxII+EtSRqqP22WQaIcAvVl3BLMfpOdZTRtGx+G7aD",
	"suaiq/c9yutD6xjj7qD9bxJegB+m3bMwOvTe/Lq6KkAJaQvGiDQw+WzYC9By3auzOsq6/Al9KLrVz+wv",
	"GITKRsDXD2blHGEaWaJPy3tLwLb1Pa9Zg9qVeWkUJzPy6uHi5mbx8fPFPP7n8u3ycvH5chHfLuYHcrg7",
	"/BsAAP//F8WAJH8bAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
