//go:build go1.22

// Package sentinel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sentinel

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for Decision.
const (
	Approve   Decision = "approve"
	Escalate  Decision = "escalate"
	Modify    Decision = "modify"
	Reject    Decision = "reject"
	Terminate Decision = "terminate"
)

// Defines values for Status.
const (
	Completed  Status = "completed"
	Processing Status = "processing"
	Queued     Status = "queued"
	Timeout    Status = "timeout"
)

// Arguments defines model for Arguments.
type Arguments struct {
	Cmd  *string `json:"cmd,omitempty"`
	Code *string `json:"code,omitempty"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Content   string      `json:"content"`
	Role      string      `json:"role"`
	Source    *string     `json:"source,omitempty"`
	ToolCalls *[]ToolCall `json:"tool_calls,omitempty"`
}

// Choice defines model for Choice.
type Choice struct {
	Message    AssistantMessage `json:"message"`
	StopReason *string          `json:"stop_reason,omitempty"`
}

// CodeSnippet defines model for CodeSnippet.
type CodeSnippet struct {
	Text string `json:"text"`
}

// Decision defines model for Decision.
type Decision string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Status string `json:"status"`
}

// HubStats defines model for HubStats.
type HubStats struct {
	AssignedReviews    map[string]int `json:"assigned_reviews"`
	BusyClients        int            `json:"busy_clients"`
	CompletedReviews   int            `json:"completed_reviews"`
	ConnectedClients   int            `json:"connected_clients"`
	FreeClients        int            `json:"free_clients"`
	QueuedReviews      int            `json:"queued_reviews"`
	ReviewDistribution map[string]int `json:"review_distribution"`
	StoredReviews      int            `json:"stored_reviews"`
}

// LLMExplanation defines model for LLMExplanation.
type LLMExplanation struct {
	Explanation string  `json:"explanation"`
	Score       float32 `json:"score"`
}

// Message defines model for Message.
type Message struct {
	Content    string      `json:"content"`
	Function   *string     `json:"function,omitempty"`
	Role       string      `json:"role"`
	Source     *string     `json:"source,omitempty"`
	ToolCallId *string     `json:"tool_call_id,omitempty"`
	ToolCalls  *[]ToolCall `json:"tool_calls,omitempty"`
}

// Output defines model for Output.
type Output struct {
	Choices *[]Choice `json:"choices,omitempty"`
	Model   *string   `json:"model,omitempty"`
	Usage   *Usage    `json:"usage,omitempty"`
}

// Review defines model for Review.
type Review struct {
	Id      string        `json:"id"`
	Request ReviewRequest `json:"request"`
}

// ReviewRequest defines model for ReviewRequest.
type ReviewRequest struct {
	AgentId      string       `json:"agent_id"`
	LastMessages []Message    `json:"last_messages"`
	TaskState    TaskState    `json:"task_state"`
	ToolChoices  []ToolChoice `json:"tool_choices"`
}

// ReviewResult defines model for ReviewResult.
type ReviewResult struct {
	Decision   Decision   `json:"decision"`
	Id         string     `json:"id"`
	Reasoning  string     `json:"reasoning"`
	ToolChoice ToolChoice `json:"tool_choice"`
}

// ReviewStatusResponse defines model for ReviewStatusResponse.
type ReviewStatusResponse struct {
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// Status defines model for Status.
type Status string

// TaskState defines model for TaskState.
type TaskState struct {
	Completed  bool                    `json:"completed"`
	Messages   []Message               `json:"messages"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Output     Output                  `json:"output"`
	Store      *map[string]interface{} `json:"store,omitempty"`
	ToolChoice *ToolChoice             `json:"tool_choice,omitempty"`
	Tools      []Tool                  `json:"tools"`
}

// Tool defines model for Tool.
type Tool struct {
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	Description *string                 `json:"description,omitempty"`
	Name        string                  `json:"name"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Arguments  map[string]interface{} `json:"arguments"`
	Function   string                 `json:"function"`
	Id         string                 `json:"id"`
	ParseError *string                `json:"parse_error,omitempty"`
	Type       string                 `json:"type"`
}

// ToolChoice defines model for ToolChoice.
type ToolChoice struct {
	Arguments Arguments `json:"arguments"`
	Function  string    `json:"function"`
	Id        string    `json:"id"`
	Type      string    `json:"type"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

// GetReviewResultParams defines parameters for GetReviewResult.
type GetReviewResultParams struct {
	Id string `form:"id" json:"id"`
}

// GetLLMExplanationJSONRequestBody defines body for GetLLMExplanation for application/json ContentType.
type GetLLMExplanationJSONRequestBody = CodeSnippet

// SubmitReviewJSONRequestBody defines body for SubmitReview for application/json ContentType.
type SubmitReviewJSONRequestBody = ReviewRequest

// SubmitReviewLLMJSONRequestBody defines body for SubmitReviewLLM for application/json ContentType.
type SubmitReviewLLMJSONRequestBody = ReviewRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get an explanation and danger score for a code snippet
	// (POST /api/explain)
	GetLLMExplanation(w http.ResponseWriter, r *http.Request)
	// Submit a review request for human review
	// (POST /api/review/human)
	SubmitReview(w http.ResponseWriter, r *http.Request)
	// Submit a review request for LLM review
	// (POST /api/review/llm)
	SubmitReviewLLM(w http.ResponseWriter, r *http.Request)
	// Get all LLM review results
	// (GET /api/review/llm/list)
	GetLLMReviews(w http.ResponseWriter, r *http.Request)
	// Get the status of a review request
	// (GET /api/review/status)
	GetReviewResult(w http.ResponseWriter, r *http.Request, params GetReviewResultParams)
	// Get hub statistics
	// (GET /api/stats)
	GetHubStats(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetLLMExplanation operation middleware
func (siw *ServerInterfaceWrapper) GetLLMExplanation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMExplanation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitReview operation middleware
func (siw *ServerInterfaceWrapper) SubmitReview(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReview(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubmitReviewLLM operation middleware
func (siw *ServerInterfaceWrapper) SubmitReviewLLM(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReviewLLM(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLLMReviews operation middleware
func (siw *ServerInterfaceWrapper) GetLLMReviews(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMReviews(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewResult operation middleware
func (siw *ServerInterfaceWrapper) GetReviewResult(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetReviewResultParams

	// ------------- Required query parameter "id" -------------

	if paramValue := r.URL.Query().Get("id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "id", r.URL.Query(), &params.Id)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewResult(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHubStats operation middleware
func (siw *ServerInterfaceWrapper) GetHubStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHubStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/api/explain", wrapper.GetLLMExplanation)
	m.HandleFunc("POST "+options.BaseURL+"/api/review/human", wrapper.SubmitReview)
	m.HandleFunc("POST "+options.BaseURL+"/api/review/llm", wrapper.SubmitReviewLLM)
	m.HandleFunc("GET "+options.BaseURL+"/api/review/llm/list", wrapper.GetLLMReviews)
	m.HandleFunc("GET "+options.BaseURL+"/api/review/status", wrapper.GetReviewResult)
	m.HandleFunc("GET "+options.BaseURL+"/api/stats", wrapper.GetHubStats)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYTW/bOBP+KwLfHo04fbcn39JusC3gooHddg9FINDS2GZLkSo5zNYo/N8XJPUtUna+",
	"ih72FEcazzzzzHD4jH+STBalFCBQk8VPorM9FNR9vFI7U9TPSyVLUMjA/ZcVuf2DhxLIgmhUTOzIcUYy",
	"mUPgxXFWP5Gbr5ChNb3SmmmkAt+D1nQHgSBSIAgMBlKSQ/CFlkZl4VcoJU8zyrnzzhAK9+GFgi1ZkP/N",
	"WyLmFQvzj1LyN5Rz0mZAlaIHl5KC74YpyMniS4O1QnYbSPjNXrIskGbR5j8FZcSXTRZlmSqgWoow612I",
	"dZwgNpnDWrCyBBwDRPiBp907q5DvPyFjmnmEIExhjWlZKnkHli5wdjMCOqOcon2GoAom/OdC5mx76Dhu",
	"63mtlFQr0KUUOsCrRopGnwZe2YWgvzWbNdLQAaBas52APFVwx+Af/yzPGTIpKL/p8+fdMoGwA0VCh2Fj",
	"9CHNOKtP2/grtiM4YD9iyEwIyKzZpLetApi2+G7AnArmX6Y5s8xuDFZFfgQPGqWajjo+d4N8R9BHXgfp",
	"D9ifjWsbzjRUk1ATLZfvr3+UnApaE9RvJei/HE+0TKruQBOm2ASY6LqpvxSC86BxuzUiiwJ81CxOWf47",
	"DusPBksTmIWZG+LnY6qG/giRG2zAg6mbc66DT/4OCB2ilWvGMfYI05YZ0HgqoPe6qoyHlLKctJ5uo6BW",
	"bazBPN2BwFgvcKoxra6v86nv3JND7pHqb6md+ydp/kj1t7UzbHrynh3gujLSBQMSGxJ6CAdxh3RMka0N",
	"D3Cddy7kKeTNxX2cxXvHag/7T/wMN7LnXJZCrdVg7nvtIogTsXY3fFwpRJJrBcQUcu88jHpCWqwb57Um",
	"8tcWmVlwGWhtUXTuGJs5K0AaDIqhtlEDg7120Wa5kZIDdaV9yoNVANKcIo3LAFQGAnTIZt5ORa6mci0U",
	"7h3lgQ3pv3i/I3/ysDe0194bErpFD7WOcz+eoOilCeh705KDzhQroxe8oAWc1tHOKobX3ctjzN0N816Q",
	"JwVJ5DyXVGlIwW4N4XHlHpxK0x3sJvysk0PlIUpBZP/rkTC5ATaGDyTgGRP8FNaUTJQGU5TfQERWAN/z",
	"kyYokfIJiyH+bsxhgIG3cSrWGxNb6QIxtMqWrEEgE8CTq5t3ZEbuQPnrk7y8uLy4dFmUIGjJyIL8cXF5",
	"8dIOcYp7h3ZOSzZ34px58S+9/rE0ObX+LicL8hfgYE9o5NRrmR8G+pyWJWeZs5t/rZZ/3yUn9Whn0T/2",
	"mbMnzT3w16QD///LyycLPcjPRe9NHrspJZ01JlGAisEd5Ik2mb0St4Zzd8+8ekJc/Z8RArBe0zxRHd2r",
	"TVFQdfBVS6joYaYiT3IqdqASt4MlW6kSmmQyh0Q3xM98W/i1cb43BZ3ojbXZFAwrVf88bTEU97+0MYIi",
	"LVAHb5d4nTRoiV5ZPGEJTTy/dfFcKRzX1YtRITgvzivDcvn+v0qEK/HbHM6pLrCTJt4Dc858A+wgOqpX",
	"nd+GHlGNs/RkdfTHinI8QZnGRG4Tynknx0S5TVCHplfcsEtKuwrFKOmtnE5r0QIQlCaLL1YHkIVdcNSB",
	"1HKy/cmg7e1Zh5mhSLl99r6vwMf73bMweS29+nWdX4ES0ra0EXmguriHGrRtisFJaKus6x+5Y9Vtfgh/",
	"xiI0MQK5vjUblwjTyLJ4BUYE7Hvf8541qLu6L43iZEFe/Ly6uVl9+Hy1TP++fr2+Xn2+XqWfVssjOd4e",
	"/w0AAP//kp6jRyEbAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
