//go:build go1.22

// Package sentinel provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sentinel

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Decision.
const (
	Approve   Decision = "approve"
	Escalate  Decision = "escalate"
	Modify    Decision = "modify"
	Reject    Decision = "reject"
	Terminate Decision = "terminate"
)

// Defines values for LLMMessageRole.
const (
	Assistant LLMMessageRole = "assistant"
	System    LLMMessageRole = "system"
	User      LLMMessageRole = "user"
)

// Defines values for Status.
const (
	Assigned  Status = "assigned"
	Completed Status = "completed"
	Failed    Status = "failed"
	Pending   Status = "pending"
	Timeout   Status = "timeout"
)

// Defines values for SupervisorType.
const (
	ClientSupervisor SupervisorType = "client_supervisor"
	HumanSupervisor  SupervisorType = "human_supervisor"
	NoSupervisor     SupervisorType = "no_supervisor"
)

// Arguments defines model for Arguments.
type Arguments struct {
	Cmd  *string `json:"cmd,omitempty"`
	Code *string `json:"code,omitempty"`
}

// AssistantMessage defines model for AssistantMessage.
type AssistantMessage struct {
	Content   string      `json:"content"`
	Role      string      `json:"role"`
	Source    *string     `json:"source,omitempty"`
	ToolCalls *[]ToolCall `json:"tool_calls,omitempty"`
}

// Choice defines model for Choice.
type Choice struct {
	Message    AssistantMessage `json:"message"`
	StopReason *string          `json:"stop_reason,omitempty"`
}

// CreateSupervisionResult defines model for CreateSupervisionResult.
type CreateSupervisionResult struct {
	ExecutionId       openapi_types.UUID `json:"execution_id"`
	RunId             openapi_types.UUID `json:"run_id"`
	SupervisionResult SupervisionResult  `json:"supervision_result"`
	SupervisorId      openapi_types.UUID `json:"supervisor_id"`
	ToolId            openapi_types.UUID `json:"tool_id"`
}

// Decision defines model for Decision.
type Decision string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Details *string `json:"details,omitempty"`
	Error   string  `json:"error"`
}

// Execution defines model for Execution.
type Execution struct {
	CreatedAt *time.Time          `json:"created_at,omitempty"`
	Id        openapi_types.UUID  `json:"id"`
	RunId     *openapi_types.UUID `json:"run_id,omitempty"`
	Status    *Status             `json:"status,omitempty"`
	ToolId    *openapi_types.UUID `json:"tool_id,omitempty"`
}

// ExecutionSupervisions defines model for ExecutionSupervisions.
type ExecutionSupervisions struct {
	ExecutionId openapi_types.UUID `json:"execution_id"`

	// Supervisions A list of supervision chains. Each chain is a list of supervisions that took place in a chain.
	Supervisions []SupervisionChain `json:"supervisions"`
}

// HubStats defines model for HubStats.
type HubStats struct {
	AssignedReviews       map[string]int `json:"assigned_reviews"`
	AssignedReviewsCount  int            `json:"assigned_reviews_count"`
	BusyClients           int            `json:"busy_clients"`
	CompletedReviewsCount int            `json:"completed_reviews_count"`
	ConnectedClients      int            `json:"connected_clients"`
	FreeClients           int            `json:"free_clients"`
	PendingReviewsCount   int            `json:"pending_reviews_count"`
	ReviewDistribution    map[string]int `json:"review_distribution"`
}

// LLMExplanationRequest defines model for LLMExplanationRequest.
type LLMExplanationRequest struct {
	Text string `json:"text"`
}

// LLMExplanationResponse defines model for LLMExplanationResponse.
type LLMExplanationResponse struct {
	Explanation *string `json:"explanation,omitempty"`
}

// LLMMessage defines model for LLMMessage.
type LLMMessage struct {
	Content string              `json:"content"`
	Id      *openapi_types.UUID `json:"id,omitempty"`
	Role    LLMMessageRole      `json:"role"`
}

// LLMMessageRole defines model for LLMMessage.Role.
type LLMMessageRole string

// Message defines model for Message.
type Message struct {
	Content    string      `json:"content"`
	Function   *string     `json:"function,omitempty"`
	Role       string      `json:"role"`
	Source     *string     `json:"source,omitempty"`
	ToolCallId *string     `json:"tool_call_id,omitempty"`
	ToolCalls  *[]ToolCall `json:"tool_calls,omitempty"`
}

// Output defines model for Output.
type Output struct {
	Choices *[]Choice `json:"choices,omitempty"`
	Model   *string   `json:"model,omitempty"`
	Usage   *Usage    `json:"usage,omitempty"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
}

// ProjectCreate defines model for ProjectCreate.
type ProjectCreate struct {
	Name string `json:"name"`
}

// Run defines model for Run.
type Run struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	ProjectId openapi_types.UUID `json:"project_id"`
}

// Status defines model for Status.
type Status string

// Supervision defines model for Supervision.
type Supervision struct {
	Request  SupervisionRequest  `json:"request"`
	Result   *SupervisionResult  `json:"result,omitempty"`
	Statuses []SupervisionStatus `json:"statuses"`
}

// SupervisionChain defines model for SupervisionChain.
type SupervisionChain = []Supervision

// SupervisionRequest defines model for SupervisionRequest.
type SupervisionRequest struct {
	ExecutionId  openapi_types.UUID  `json:"execution_id"`
	Id           *openapi_types.UUID `json:"id,omitempty"`
	Messages     []LLMMessage        `json:"messages"`
	RunId        openapi_types.UUID  `json:"run_id"`
	Status       *SupervisionStatus  `json:"status,omitempty"`
	SupervisorId openapi_types.UUID  `json:"supervisor_id"`
	TaskState    TaskState           `json:"task_state"`
	ToolRequests []ToolRequest       `json:"tool_requests"`
}

// SupervisionResult defines model for SupervisionResult.
type SupervisionResult struct {
	CreatedAt            time.Time          `json:"created_at"`
	Decision             Decision           `json:"decision"`
	Id                   openapi_types.UUID `json:"id"`
	Reasoning            string             `json:"reasoning"`
	SupervisionRequestId openapi_types.UUID `json:"supervision_request_id"`

	// Toolrequest A tool request is a request to use a tool. It must be approved by a supervisor.
	Toolrequest ToolRequest `json:"toolrequest"`
}

// SupervisionStatus defines model for SupervisionStatus.
type SupervisionStatus struct {
	CreatedAt            time.Time           `json:"created_at"`
	Id                   int                 `json:"id"`
	Status               Status              `json:"status"`
	SupervisionRequestId *openapi_types.UUID `json:"supervision_request_id,omitempty"`
}

// Supervisor defines model for Supervisor.
type Supervisor struct {
	Attributes  map[string]interface{} `json:"attributes"`
	Code        string                 `json:"code"`
	CreatedAt   time.Time              `json:"created_at"`
	Description string                 `json:"description"`
	Id          *openapi_types.UUID    `json:"id,omitempty"`
	Name        string                 `json:"name"`

	// Type The type of supervisor. ClientSupervisor means that the supervision is done client side and the server is merely informed. Other supervisor types are handled serverside, e.g. HumanSupervisor means that a human will review the request via the Sentinel UI.
	Type SupervisorType `json:"type"`
}

// SupervisorChain defines model for SupervisorChain.
type SupervisorChain struct {
	Supervisors []Supervisor `json:"supervisors"`
}

// SupervisorChainAssignment defines model for SupervisorChainAssignment.
type SupervisorChainAssignment = [][]openapi_types.UUID

// SupervisorChains defines model for SupervisorChains.
type SupervisorChains = []SupervisorChain

// SupervisorType The type of supervisor. ClientSupervisor means that the supervision is done client side and the server is merely informed. Other supervisor types are handled serverside, e.g. HumanSupervisor means that a human will review the request via the Sentinel UI.
type SupervisorType string

// TaskState defines model for TaskState.
type TaskState struct {
	Completed  bool                    `json:"completed"`
	Messages   []Message               `json:"messages"`
	Metadata   *map[string]interface{} `json:"metadata,omitempty"`
	Output     Output                  `json:"output"`
	Store      *map[string]interface{} `json:"store,omitempty"`
	ToolChoice *ToolChoice             `json:"tool_choice,omitempty"`
	Tools      []Tool                  `json:"tools"`
}

// Tool defines model for Tool.
type Tool struct {
	// Attributes Attributes of the tool that requests to this tool will have
	Attributes  *map[string]interface{} `json:"attributes,omitempty"`
	CreatedAt   *time.Time              `json:"created_at,omitempty"`
	Description string                  `json:"description"`
	Id          *openapi_types.UUID     `json:"id,omitempty"`

	// IgnoredAttributes Attributes of the tool that will not be shown in the UI for requests to this tool
	IgnoredAttributes *[]string `json:"ignored_attributes,omitempty"`
	Name              string    `json:"name"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	Arguments  map[string]interface{} `json:"arguments"`
	Function   string                 `json:"function"`
	Id         string                 `json:"id"`
	ParseError *string                `json:"parse_error,omitempty"`
	Type       string                 `json:"type"`
}

// ToolChoice defines model for ToolChoice.
type ToolChoice struct {
	Arguments Arguments `json:"arguments"`
	Function  string    `json:"function"`
	Id        string    `json:"id"`
	Type      string    `json:"type"`
}

// ToolRequest A tool request is a request to use a tool. It must be approved by a supervisor.
type ToolRequest struct {
	Arguments            map[string]interface{} `json:"arguments"`
	Id                   *openapi_types.UUID    `json:"id,omitempty"`
	MessageId            *openapi_types.UUID    `json:"message_id,omitempty"`
	SupervisionRequestId *openapi_types.UUID    `json:"supervision_request_id,omitempty"`
	ToolId               openapi_types.UUID     `json:"tool_id"`
}

// Usage defines model for Usage.
type Usage struct {
	InputTokens  int `json:"input_tokens"`
	OutputTokens int `json:"output_tokens"`
	TotalTokens  int `json:"total_tokens"`
}

// GetSupervisionRequestsParams defines parameters for GetSupervisionRequests.
type GetSupervisionRequestsParams struct {
	Type *SupervisorType `form:"type,omitempty" json:"type,omitempty"`
}

// CreateExecutionJSONBody defines parameters for CreateExecution.
type CreateExecutionJSONBody struct {
	ToolId *openapi_types.UUID `json:"toolId,omitempty"`
}

// GetSupervisorsParams defines parameters for GetSupervisors.
type GetSupervisorsParams struct {
	// ProjectId Project context for the supervisors query
	ProjectId openapi_types.UUID `form:"projectId" json:"projectId"`
}

// GetToolsParams defines parameters for GetTools.
type GetToolsParams struct {
	// ProjectId Project context for the tools query
	ProjectId openapi_types.UUID `form:"projectId" json:"projectId"`
}

// GetLLMExplanationJSONRequestBody defines body for GetLLMExplanation for application/json ContentType.
type GetLLMExplanationJSONRequestBody = LLMExplanationRequest

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreate

// CreateSupervisionRequestJSONRequestBody defines body for CreateSupervisionRequest for application/json ContentType.
type CreateSupervisionRequestJSONRequestBody = SupervisionRequest

// CreateSupervisionResultJSONRequestBody defines body for CreateSupervisionResult for application/json ContentType.
type CreateSupervisionResultJSONRequestBody = CreateSupervisionResult

// CreateExecutionJSONRequestBody defines body for CreateExecution for application/json ContentType.
type CreateExecutionJSONRequestBody CreateExecutionJSONBody

// CreateRunToolSupervisorsJSONRequestBody defines body for CreateRunToolSupervisors for application/json ContentType.
type CreateRunToolSupervisorsJSONRequestBody = SupervisorChainAssignment

// CreateSupervisorJSONRequestBody defines body for CreateSupervisor for application/json ContentType.
type CreateSupervisorJSONRequestBody = Supervisor

// CreateToolJSONRequestBody defines body for CreateTool for application/json ContentType.
type CreateToolJSONRequestBody = Tool

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get supervision info for an execution
	// (GET /api/executions/{executionId}/supervisions)
	GetExecutionSupervisions(w http.ResponseWriter, r *http.Request, executionId openapi_types.UUID)
	// Get LLM explanation
	// (POST /api/llm/explanation)
	GetLLMExplanation(w http.ResponseWriter, r *http.Request)
	// Get the OpenAPI schema
	// (GET /api/openapi.yaml)
	GetOpenAPI(w http.ResponseWriter, r *http.Request)
	// List all projects
	// (GET /api/projects)
	GetProjects(w http.ResponseWriter, r *http.Request)
	// Create a new project
	// (POST /api/projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// Get project by ID
	// (GET /api/projects/{projectId})
	GetProject(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Get runs for a project
	// (GET /api/projects/{projectId}/runs)
	GetProjectRuns(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// Create a new run for a project
	// (POST /api/projects/{projectId}/runs)
	CreateRun(w http.ResponseWriter, r *http.Request, projectId openapi_types.UUID)
	// List all supervisor requests
	// (GET /api/reviews)
	GetSupervisionRequests(w http.ResponseWriter, r *http.Request, params GetSupervisionRequestsParams)
	// Create a supervisor request
	// (POST /api/reviews)
	CreateSupervisionRequest(w http.ResponseWriter, r *http.Request)
	// Get supervision request by ID
	// (GET /api/reviews/{reviewId})
	GetSupervisionRequest(w http.ResponseWriter, r *http.Request, reviewId openapi_types.UUID)
	// Get supervision results
	// (GET /api/reviews/{reviewId}/results)
	GetSupervisionResults(w http.ResponseWriter, r *http.Request, reviewId openapi_types.UUID)
	// Create a supervision result
	// (POST /api/reviews/{reviewId}/results)
	CreateSupervisionResult(w http.ResponseWriter, r *http.Request, reviewId openapi_types.UUID)
	// Get supervision status
	// (GET /api/reviews/{reviewId}/status)
	GetSupervisionStatus(w http.ResponseWriter, r *http.Request, reviewId openapi_types.UUID)
	// Get tool requests for a supervisor
	// (GET /api/reviews/{reviewId}/toolrequests)
	GetReviewToolRequests(w http.ResponseWriter, r *http.Request, reviewId openapi_types.UUID)
	// Get run by ID
	// (GET /api/runs/{runId})
	GetRun(w http.ResponseWriter, r *http.Request, runId openapi_types.UUID)
	// Get executions for a run
	// (GET /api/runs/{runId}/executions)
	GetRunExecutions(w http.ResponseWriter, r *http.Request, runId openapi_types.UUID)
	// Create an execution
	// (POST /api/runs/{runId}/executions)
	CreateExecution(w http.ResponseWriter, r *http.Request, runId openapi_types.UUID)
	// Get tools for a run
	// (GET /api/runs/{runId}/tools)
	GetRunTools(w http.ResponseWriter, r *http.Request, runId openapi_types.UUID)
	// Get the supervisors assigned to a tool, grouped by chain
	// (GET /api/runs/{runId}/tools/{toolId}/supervisors)
	GetRunToolSupervisors(w http.ResponseWriter, r *http.Request, runId openapi_types.UUID, toolId openapi_types.UUID)
	// Assign supervisors to a tool for a given run
	// (POST /api/runs/{runId}/tools/{toolId}/supervisors)
	CreateRunToolSupervisors(w http.ResponseWriter, r *http.Request, runId openapi_types.UUID, toolId openapi_types.UUID)
	// Get hub stats
	// (GET /api/stats)
	GetHubStats(w http.ResponseWriter, r *http.Request)
	// List all supervisors available for a project
	// (GET /api/supervisors)
	GetSupervisors(w http.ResponseWriter, r *http.Request, params GetSupervisorsParams)
	// Create a new supervisor
	// (POST /api/supervisors)
	CreateSupervisor(w http.ResponseWriter, r *http.Request)
	// Get supervisor by ID
	// (GET /api/supervisors/{supervisorId})
	GetSupervisor(w http.ResponseWriter, r *http.Request, supervisorId openapi_types.UUID)
	// Get the Swagger UI
	// (GET /api/swagger-ui)
	GetSwaggerDocs(w http.ResponseWriter, r *http.Request)
	// List all tools available for a project
	// (GET /api/tools)
	GetTools(w http.ResponseWriter, r *http.Request, params GetToolsParams)
	// Create a new tool
	// (POST /api/tools)
	CreateTool(w http.ResponseWriter, r *http.Request)
	// Get tool by ID
	// (GET /api/tools/{toolId})
	GetTool(w http.ResponseWriter, r *http.Request, toolId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetExecutionSupervisions operation middleware
func (siw *ServerInterfaceWrapper) GetExecutionSupervisions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "executionId" -------------
	var executionId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "executionId", r.PathValue("executionId"), &executionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "executionId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetExecutionSupervisions(w, r, executionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLLMExplanation operation middleware
func (siw *ServerInterfaceWrapper) GetLLMExplanation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMExplanation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOpenAPI operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPI(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOpenAPI(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProjects operation middleware
func (siw *ServerInterfaceWrapper) GetProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProjectRuns operation middleware
func (siw *ServerInterfaceWrapper) GetProjectRuns(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProjectRuns(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRun operation middleware
func (siw *ServerInterfaceWrapper) CreateRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "projectId" -------------
	var projectId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "projectId", r.PathValue("projectId"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRun(w, r, projectId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupervisionRequests operation middleware
func (siw *ServerInterfaceWrapper) GetSupervisionRequests(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSupervisionRequestsParams

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameter("form", true, false, "type", r.URL.Query(), &params.Type)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupervisionRequests(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSupervisionRequest operation middleware
func (siw *ServerInterfaceWrapper) CreateSupervisionRequest(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSupervisionRequest(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupervisionRequest operation middleware
func (siw *ServerInterfaceWrapper) GetSupervisionRequest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", r.PathValue("reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupervisionRequest(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupervisionResults operation middleware
func (siw *ServerInterfaceWrapper) GetSupervisionResults(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", r.PathValue("reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupervisionResults(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSupervisionResult operation middleware
func (siw *ServerInterfaceWrapper) CreateSupervisionResult(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", r.PathValue("reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSupervisionResult(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupervisionStatus operation middleware
func (siw *ServerInterfaceWrapper) GetSupervisionStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", r.PathValue("reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupervisionStatus(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReviewToolRequests operation middleware
func (siw *ServerInterfaceWrapper) GetReviewToolRequests(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "reviewId" -------------
	var reviewId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "reviewId", r.PathValue("reviewId"), &reviewId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "reviewId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReviewToolRequests(w, r, reviewId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRun operation middleware
func (siw *ServerInterfaceWrapper) GetRun(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRun(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunExecutions operation middleware
func (siw *ServerInterfaceWrapper) GetRunExecutions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunExecutions(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateExecution operation middleware
func (siw *ServerInterfaceWrapper) CreateExecution(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateExecution(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunTools operation middleware
func (siw *ServerInterfaceWrapper) GetRunTools(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunTools(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRunToolSupervisors operation middleware
func (siw *ServerInterfaceWrapper) GetRunToolSupervisors(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// ------------- Path parameter "toolId" -------------
	var toolId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "toolId", r.PathValue("toolId"), &toolId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toolId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRunToolSupervisors(w, r, runId, toolId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRunToolSupervisors operation middleware
func (siw *ServerInterfaceWrapper) CreateRunToolSupervisors(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "runId" -------------
	var runId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "runId", r.PathValue("runId"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "runId", Err: err})
		return
	}

	// ------------- Path parameter "toolId" -------------
	var toolId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "toolId", r.PathValue("toolId"), &toolId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toolId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRunToolSupervisors(w, r, runId, toolId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHubStats operation middleware
func (siw *ServerInterfaceWrapper) GetHubStats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHubStats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupervisors operation middleware
func (siw *ServerInterfaceWrapper) GetSupervisors(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSupervisorsParams

	// ------------- Required query parameter "projectId" -------------

	if paramValue := r.URL.Query().Get("projectId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "projectId"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "projectId", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupervisors(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSupervisor operation middleware
func (siw *ServerInterfaceWrapper) CreateSupervisor(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSupervisor(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSupervisor operation middleware
func (siw *ServerInterfaceWrapper) GetSupervisor(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "supervisorId" -------------
	var supervisorId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "supervisorId", r.PathValue("supervisorId"), &supervisorId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "supervisorId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSupervisor(w, r, supervisorId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetSwaggerDocs operation middleware
func (siw *ServerInterfaceWrapper) GetSwaggerDocs(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSwaggerDocs(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTools operation middleware
func (siw *ServerInterfaceWrapper) GetTools(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetToolsParams

	// ------------- Required query parameter "projectId" -------------

	if paramValue := r.URL.Query().Get("projectId"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "projectId"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "projectId", r.URL.Query(), &params.ProjectId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "projectId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTools(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTool operation middleware
func (siw *ServerInterfaceWrapper) CreateTool(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTool(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTool operation middleware
func (siw *ServerInterfaceWrapper) GetTool(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "toolId" -------------
	var toolId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "toolId", r.PathValue("toolId"), &toolId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "toolId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTool(w, r, toolId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/api/executions/{executionId}/supervisions", wrapper.GetExecutionSupervisions)
	m.HandleFunc("POST "+options.BaseURL+"/api/llm/explanation", wrapper.GetLLMExplanation)
	m.HandleFunc("GET "+options.BaseURL+"/api/openapi.yaml", wrapper.GetOpenAPI)
	m.HandleFunc("GET "+options.BaseURL+"/api/projects", wrapper.GetProjects)
	m.HandleFunc("POST "+options.BaseURL+"/api/projects", wrapper.CreateProject)
	m.HandleFunc("GET "+options.BaseURL+"/api/projects/{projectId}", wrapper.GetProject)
	m.HandleFunc("GET "+options.BaseURL+"/api/projects/{projectId}/runs", wrapper.GetProjectRuns)
	m.HandleFunc("POST "+options.BaseURL+"/api/projects/{projectId}/runs", wrapper.CreateRun)
	m.HandleFunc("GET "+options.BaseURL+"/api/reviews", wrapper.GetSupervisionRequests)
	m.HandleFunc("POST "+options.BaseURL+"/api/reviews", wrapper.CreateSupervisionRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/reviews/{reviewId}", wrapper.GetSupervisionRequest)
	m.HandleFunc("GET "+options.BaseURL+"/api/reviews/{reviewId}/results", wrapper.GetSupervisionResults)
	m.HandleFunc("POST "+options.BaseURL+"/api/reviews/{reviewId}/results", wrapper.CreateSupervisionResult)
	m.HandleFunc("GET "+options.BaseURL+"/api/reviews/{reviewId}/status", wrapper.GetSupervisionStatus)
	m.HandleFunc("GET "+options.BaseURL+"/api/reviews/{reviewId}/toolrequests", wrapper.GetReviewToolRequests)
	m.HandleFunc("GET "+options.BaseURL+"/api/runs/{runId}", wrapper.GetRun)
	m.HandleFunc("GET "+options.BaseURL+"/api/runs/{runId}/executions", wrapper.GetRunExecutions)
	m.HandleFunc("POST "+options.BaseURL+"/api/runs/{runId}/executions", wrapper.CreateExecution)
	m.HandleFunc("GET "+options.BaseURL+"/api/runs/{runId}/tools", wrapper.GetRunTools)
	m.HandleFunc("GET "+options.BaseURL+"/api/runs/{runId}/tools/{toolId}/supervisors", wrapper.GetRunToolSupervisors)
	m.HandleFunc("POST "+options.BaseURL+"/api/runs/{runId}/tools/{toolId}/supervisors", wrapper.CreateRunToolSupervisors)
	m.HandleFunc("GET "+options.BaseURL+"/api/stats", wrapper.GetHubStats)
	m.HandleFunc("GET "+options.BaseURL+"/api/supervisors", wrapper.GetSupervisors)
	m.HandleFunc("POST "+options.BaseURL+"/api/supervisors", wrapper.CreateSupervisor)
	m.HandleFunc("GET "+options.BaseURL+"/api/supervisors/{supervisorId}", wrapper.GetSupervisor)
	m.HandleFunc("GET "+options.BaseURL+"/api/swagger-ui", wrapper.GetSwaggerDocs)
	m.HandleFunc("GET "+options.BaseURL+"/api/tools", wrapper.GetTools)
	m.HandleFunc("POST "+options.BaseURL+"/api/tools", wrapper.CreateTool)
	m.HandleFunc("GET "+options.BaseURL+"/api/tools/{toolId}", wrapper.GetTool)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9xcS2/buvL/KoT+/6WP3XPvWWXX2xa3AVK0SNLVQWDQ0tjmqUSqfCQ1gnz3Cz4kURIl",
	"0U7i2lnFjzE5jx9nhjOjPCYpK0pGgUqRXDwmIt1Cgc3L93yjiurzkrMSuCRg3qVFpv/IXQnJRSIkJ3ST",
	"PM2SlGUQ+OJpVn3CVv9AKjXpeyGIkJjKLyAE3kBgE0YlUBnciLMcgl8Ipnga/koyli9TnOdmdSKhMC/+",
	"n8M6uUj+b9EoYuG0sLhlLP+A8zxpJMCc450RicNPRThkycXfNa+Os7uAwB+2jKQBMYtG/jFWevrSwkpW",
	"LjlgwWhY6z6L1T5B3jhgCTeqBH5PBGH0GoTKZZ9Z+AWpkoTRJTEIWDNeYJlcJEqRLJkFDKWiSUWz/ZLX",
	"+4/ppM+wtwzjsRsbYETRdlTqhJu11dIs2GUmKGPIHh8hNTRG5VQVejNclpzdg4YYGLpZIoEXhGKpPyxY",
	"RtY7zYtIca4/uwuI+olzxq9BlIyKABYzkJjY89H7KeifTsPMkoWE+lQpKXDUDf6yJZYtI2RYwh+SFBCy",
	"2isAUGKpJn3CjaV6Dm5INq4gD9fiBc6g6CyXgUg5Ka0pkvcoJ0IitkYeHUq3mFAxR59wurVvEBEIh2gF",
	"klsskWTsBypznAIiFGH7o3kyi/O0nsgf9A8nPW7nyLVkDCn3s1ppywX0iYUgGwrZksM9gQf7WZYRvTjO",
	"v7Vo3bKEStgAT0KBrbvcMmWqFcW8H6+U2C3TnFRRtk+hVZWDjFsuZZRCqolH11xzgHGKEmhG6CZmT0uy",
	"zIjG26o+3wcrsB9YOyLNkp8KlGcuEwd564OWhB019y2UhKUYVv6QggaNHwLk1dWXT7/KHFMsTfz6qUAE",
	"Iq6EX3La6xqqmF2GPD80RJEJ3NXVl4NSt1i/7TK8KvyJnZBQJLNECeBO0yYfCsS5bpjWS81qpkJqOkiS",
	"taLpgMKemaE6z35qKexXJUsVwGhqUtt4nlwq3OPIZDGQB0VXMUnyd5sZh+D6jTPz8pi5B8UFTJ9d81tD",
	"OvOZuRsWwqbrfVHi9jNUodWv1XFTs9JKc2gK1VpgUnU3dXJXeRTnw30/r0MHJrl5UblyzQopgCkZzKi9",
	"xKWvPN549eh7jP2FEffwO5ARdo8T6a3i5bdj7qISzdssqPZuXncARyFHEVDZ8xPlSDJ3k47XrhcqA6K8",
	"/A0lZMwDrsVY/FjqHSfd7i0WP24MYRWjHDr2C1Me9sehN3TtbhjusuEZrauKCdQOVUIO8YuZd60fU0Z9",
	"/d8jXTJVIP0mmHO0yg5GJ/sURyLdWMuGIX89wEbLd3ta8qVqMzJhs8bXv1Qs619b9i0WHGyCoCLtstNB",
	"r0Z64Nor7VUHRi68kisILDtQ5p0deCi8asTjS+daFWWcx2T8VlMHM6Y2p27dDnQ9nTotjVulDolt0zQO",
	"av8Izvik//SXj+DvvUmECncLqpmpX0y7kE7AG4rlbr9DZB6oGflr3zoctKtft1tA+jd+TYvxOfpgqgXN",
	"r1EBuK50baFVKyMCZYwCshUGJEgGCNPM0gG/B65JCuCQ7xChWl+QzdFXuQXubWr4EAhzQFtMsxwy92u9",
	"4AzBfDNHn1WBaZgrjLb6S/RA8hzZ8oPhwDkbdE+weX8DVBIKOfp+Odcx1GXDlvllw04yS8yC7Y8o89+H",
	"EuImGQhcpqs8uzmoK8ZywPSgvGokqSpA4gxLvLdvY/Udd2xndxN+crWnvXexF/m6IzR5gW8uzIztefmf",
	"dAdeZmRXr5Xg34xCjsIs/4zA0ilE17/Th1FDVbNjwV0lckgyJLdE2K8M1Lf43osrXpD6fbGIbKgpSLY1",
	"ES+tkYsyiVaAxJY9UESoIfl+idaMh7XhV9onXfAelYK2VoZgYEpMfSj4LeS9DshobW2gOlZiLmA51Kdq",
	"MoGIBKvefubJ4FYYVMFAg7elhNEWb014oAJeWUDvot1tIRnsVpHGNIqqN5IhJQBhQzJHlxIVShhku4Zm",
	"hlY7hP3gays7LwKj/W70h3Wq975OHZT3Nz3lRhshQ30P17EJLZVcSvYD6EAfxvr8URLJJM5HKLpA8/fs",
	"btBZrS+KXk0nS2YjInP9XZ27vP92mcwSkxsZBP45fzd/Z6QogeKSJBfJv+fv5n9qKGG5NdwucEkWdclA",
	"LB7r15fZ06LbJN2AAbrWIbY0yUXyX5DhJq1xPrgACTpl/1vrO7kwW1e13YvE2y7xFWWha51ADC7uTGnQ",
	"9HEMp/96967TqcBlmZPUsL34xw2HNOuPuaCwdMYW7SN/4+e/2kpPs+Svl2SkNagQYOCS3uOcZJWfMeAT",
	"qigw31lDtVN0umYmdGKKajuYktFG26tpvYvkTq9ksJLnxaLTFyuZCMOi3Wdz9gUh/8Oy3YspJdwyfGqf",
	"Ow2np1eEyEBHMWCiq6svyNff6UGky2EDiKurLx4SnFeZ73CRjzmHryVQ65pC6m9z52iRE7bPnE74OkQN",
	"f3qXhj/XCBl1XN8qmmdiI+riUXXb+nePPkrcREktw2nBxLCH87zhrzFCrdI7nX0GXYNt1VXqeB230O4K",
	"Htkd1JbuK9Z9hdxNDAmVpiDEWuX57sSsbHWHMKLwUFk6bOjukVs8uleX2VPE8YvKFOoVTzZPiLB6NUv4",
	"2w2t9/+r738rPvU9e80UzQIu2BlC31AuP+6PhwVXNMYnX6vIFPI0gBEVAa4V3cf7G02dM1S0ADbDDPgP",
	"Y+CpIKE19ja8g7F9X93Xig7EgmFfzBWd0mp1Ar3xzaHz1p8aGDp3PxXwXaNz1+yJE7/XTTrKgQsPkcSe",
	"P68NUTfNTzQRC7HqgcKhYOq0BdT1OtlZyC7HTdEC8yDDF3rGzypf64MhiIWOj1g82hcTOVsQI9MOulr7",
	"ZP3zECSHSzxVNffUk7oQz2NRWwTou8leDIoWdlgvPvhY6rNB0/4RqBpFnApAbYtZtbxNdFUmf1akMmo9",
	"LmxePiQOyRUfF6cwdJYxrGF/X+/TDKNFOJ+banjsbUWy6dRG61fUA3lvzsPUQ4F7QccbqxwFkF3MawO/",
	"teg1PoHcs+it1/G2F39/LMxO4b0JiMmeoH7W7cHt1gwPeWBTVCNN0YksO7buYVY6x5rHqSfNmseJ0lY/",
	"Ke7UXjxbez32CbN7XdfzAECUI2mec9+j/uLp7PTapA1z7vxzNdg8H89lP3m996MZ/LAEtvMYLmP5ZeTY",
	"TmCQ5XjFHg99fVPXX55TfrzHxEbLDdWjsiMe6NYNvL4Z5zMw8Tvod6ySzjUyGe6DPsm11MZyEguQxaM9",
	"2s0EmHvqYgI1Nx71cfAzC67rHNOpX9DqZztGsGj/50i7G3Ha2NRZv06PRzHauhYIVD1XjCRzU7EztOFM",
	"lXYS1ijBA7KPMz+6dpL6ElKy3mlnaY68VqJ50VUnIrR1aWQ8A+7+zYv9JYeSg9A6C/y7F71CM6K+ApTi",
	"PIdMr6qPQJ5DPkMPRG6N2GvChfRL9IQiaHZaAaGbagVDOzPPzQiGGJ2j2y2ItuqGN0UPW6DekwFEC3rP",
	"fuiF3dWMQ4EJzYBX8/ZcmX9PM9CKPeSMv8BZnJ1eIrTH8fYeFXtuLa97VIxZTzhbsaK3D0p1wF2E2pB7",
	"oJ041T7eVZgS1X8qGgpC9X8zekXXXe8R0MVntUKWydO7rWxr3ho1f1YrX71xkX70+A+Mumkd/JKBepBA",
	"1UhBaL7gjAZ7Rh80jZgvEAjfY5LjVQ61mspmXPS0Jw66zIfGUoYi9lhvxxTSXtdB/66pg2rnNzFuQOEh",
	"XPwc8OPNp4vH5k3k2IHZYDrr8Nc9g3vABBrOZcKA8ajGDOO90ukAVB7wZgP8D0VGoWGpPrJURD1k4OjR",
	"98uBm0mHwLAyWTgZqJrEhUR7Z38jwfCgcsv5BcAQ26HQV5VbxoPerX1a+TXCnbXHcQNds2egQ3huwc09",
	"ST7U02uXzKZ8xLEuzXe/y7qnHqxuJ4tTmqAboGqjPz39LwAA//+0d7JXH14AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
